// @generated drizzle-zero signature:sha256:4233d917aaa50aac0c420968f811881755b690390d9bc29335daa2c1c2261faa
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const demoItemsTable = {
  name: "demo_items",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    owner_user_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const labelsTable = {
  name: "labels",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    team_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    color: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const tasksTable = {
  name: "tasks",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    team_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    number: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    previous_identifiers: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    assigned_user_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    created_by_user_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    cycle_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    due_date: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    parent_task_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    label_ids: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    workflow_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    workflow_status_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    task_state: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    estimate: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    board_order: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    finished_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    source_template_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    source_template_task_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    source_template_cycle_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    source_template_sync_enabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
  },
  primaryKey: ["id"],
} as const;
const teamMembershipsTable = {
  name: "team_memberships",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    team_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    user_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const teamsTable = {
  name: "teams",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    identifier: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    next_task_number: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    previous_identifiers: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    color: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    sort_order: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const workflowStatusesTable = {
  name: "workflow_statuses",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    workflow_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    task_state: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    sort_order: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const workflowsTable = {
  name: "workflows",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    team_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    demo_items: demoItemsTable,
    labels: labelsTable,
    tasks: tasksTable,
    team_memberships: teamMembershipsTable,
    teams: teamsTable,
    workflow_statuses: workflowStatusesTable,
    workflows: workflowsTable,
  },
  relationships: {},
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "demo_items" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type DemoItem = Row<(typeof schema)["tables"]["demo_items"]>;
/**
 * Represents a row from the "labels" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Label = Row<(typeof schema)["tables"]["labels"]>;
/**
 * Represents a row from the "tasks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Task = Row<(typeof schema)["tables"]["tasks"]>;
/**
 * Represents a row from the "team_memberships" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TeamMembership = Row<(typeof schema)["tables"]["team_memberships"]>;
/**
 * Represents a row from the "teams" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Team = Row<(typeof schema)["tables"]["teams"]>;
/**
 * Represents a row from the "workflow_statuses" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type WorkflowStatus = Row<(typeof schema)["tables"]["workflow_statuses"]>;
/**
 * Represents a row from the "workflows" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Workflow = Row<(typeof schema)["tables"]["workflows"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
