// @generated drizzle-zero signature:sha256:38018f7411cc88a42a96b4e81389605d7592855b0a19ac4f289078824104b634
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const activitiesTable = {
  name: "activities",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    entity_type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    entity_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    event_type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    actor_type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    actor_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    occurred_at: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    cycle_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    metadata: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const cycleAdjustmentsTable = {
  name: "cycle_adjustments",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    cycle_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    template_task_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    lifecycle: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    overrides: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const cyclesTable = {
  name: "cycles",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    start_date: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    end_date: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    starts_at: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    ends_at: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    church_time_zone: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const demoItemsTable = {
  name: "demo_items",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    owner_user_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const focusWindowsTable = {
  name: "focus_windows",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    template_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    start_date: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    end_date: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    anchor_date: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    key_date_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const invitationTable = {
  name: "invitation",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    inviterId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "inviter_id",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const keyDateOccurrencesTable = {
  name: "key_date_occurrences",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    key_date_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    local_date: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    label: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const keyDatesTable = {
  name: "key_dates",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    schedule: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const labelsTable = {
  name: "labels",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    team_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    color: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const memberTable = {
  name: "member",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const organizationTable = {
  name: "organization",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    logo: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    metadata: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    churchTimeZone: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "church_time_zone",
    },
    completedOnboarding: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "completed_onboarding",
    },
    url: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    street: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    city: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    state: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    zip: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    countryCode: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "country_code",
    },
    latitude: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    longitude: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    size: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const tasksTable = {
  name: "tasks",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    team_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    number: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    previous_identifiers: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    assigned_user_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    created_by_user_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    cycle_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    due_date: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    parent_task_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    label_ids: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    workflow_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    workflow_status_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    task_state: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    estimate: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    board_order: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    finished_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    source_template_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    source_template_task_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    source_template_cycle_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    source_template_schedule_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    source_template_occurrence_key: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    source_template_sync_enabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
  },
  primaryKey: ["id"],
} as const;
const teamMembershipsTable = {
  name: "team_memberships",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    team_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    user_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const teamsTable = {
  name: "teams",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    identifier: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    next_task_number: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    previous_identifiers: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    color: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    sort_order: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const templateSchedulesTable = {
  name: "template_schedules",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    template_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    kind: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    recurrence: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    start_date: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    end_date: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    rule: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const templateTasksTable = {
  name: "template_tasks",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    template_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    template_team_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    assigned_user_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    label_ids: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    estimate: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    parent_template_task_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    scheduling_rule: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    placement_cycle_offset: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    placement_weekday: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const templateTeamsTable = {
  name: "template_teams",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    template_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    mapped_team_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const templatesTable = {
  name: "templates",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    recurrence: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    placement_shape: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    emailVerified: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "email_verified",
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    banned: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    banReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ban_reason",
    },
    banExpires: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "ban_expires",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const workflowStatusesTable = {
  name: "workflow_statuses",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    workflow_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    task_state: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    sort_order: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const workflowsTable = {
  name: "workflows",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    church_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    team_id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    activities: activitiesTable,
    cycle_adjustments: cycleAdjustmentsTable,
    cycles: cyclesTable,
    demo_items: demoItemsTable,
    focus_windows: focusWindowsTable,
    invitation: invitationTable,
    key_date_occurrences: keyDateOccurrencesTable,
    key_dates: keyDatesTable,
    labels: labelsTable,
    member: memberTable,
    organization: organizationTable,
    tasks: tasksTable,
    team_memberships: teamMembershipsTable,
    teams: teamsTable,
    template_schedules: templateSchedulesTable,
    template_tasks: templateTasksTable,
    template_teams: templateTeamsTable,
    templates: templatesTable,
    user: userTable,
    workflow_statuses: workflowStatusesTable,
    workflows: workflowsTable,
  },
  relationships: {},
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "activities" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Activity = Row<(typeof schema)["tables"]["activities"]>;
/**
 * Represents a row from the "cycle_adjustments" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CycleAdjustment = Row<(typeof schema)["tables"]["cycle_adjustments"]>;
/**
 * Represents a row from the "cycles" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Cycle = Row<(typeof schema)["tables"]["cycles"]>;
/**
 * Represents a row from the "demo_items" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type DemoItem = Row<(typeof schema)["tables"]["demo_items"]>;
/**
 * Represents a row from the "focus_windows" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type FocusWindow = Row<(typeof schema)["tables"]["focus_windows"]>;
/**
 * Represents a row from the "invitation" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Invitation = Row<(typeof schema)["tables"]["invitation"]>;
/**
 * Represents a row from the "key_date_occurrences" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type KeyDateOccurrence = Row<(typeof schema)["tables"]["key_date_occurrences"]>;
/**
 * Represents a row from the "key_dates" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type KeyDate = Row<(typeof schema)["tables"]["key_dates"]>;
/**
 * Represents a row from the "labels" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Label = Row<(typeof schema)["tables"]["labels"]>;
/**
 * Represents a row from the "member" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Member = Row<(typeof schema)["tables"]["member"]>;
/**
 * Represents a row from the "organization" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Organization = Row<(typeof schema)["tables"]["organization"]>;
/**
 * Represents a row from the "tasks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Task = Row<(typeof schema)["tables"]["tasks"]>;
/**
 * Represents a row from the "team_memberships" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TeamMembership = Row<(typeof schema)["tables"]["team_memberships"]>;
/**
 * Represents a row from the "teams" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Team = Row<(typeof schema)["tables"]["teams"]>;
/**
 * Represents a row from the "template_schedules" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TemplateSchedule = Row<(typeof schema)["tables"]["template_schedules"]>;
/**
 * Represents a row from the "template_tasks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TemplateTask = Row<(typeof schema)["tables"]["template_tasks"]>;
/**
 * Represents a row from the "template_teams" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TemplateTeam = Row<(typeof schema)["tables"]["template_teams"]>;
/**
 * Represents a row from the "templates" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Template = Row<(typeof schema)["tables"]["templates"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;
/**
 * Represents a row from the "workflow_statuses" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type WorkflowStatus = Row<(typeof schema)["tables"]["workflow_statuses"]>;
/**
 * Represents a row from the "workflows" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Workflow = Row<(typeof schema)["tables"]["workflows"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
