import * as drizzleSchema from "@church-task/db/schema";
import { drizzleZeroConfig } from "drizzle-zero";

export default drizzleZeroConfig(drizzleSchema, {
  casing: "snake_case",
  tables: {
    activities: true,
    demo_items: {
      _tag: true,
      created_at: true,
      created_by: true,
      deleted_at: true,
      deleted_by: true,
      id: true,
      name: true,
      owner_user_id: true,
      updated_at: true,
      updated_by: true,
    },
    cycle_adjustments: true,
    cycles: true,
    focus_windows: true,
    invitation: true,
    key_date_occurrences: true,
    key_dates: true,
    labels: true,
    member: true,
    organization: true,
    team_memberships: true,
    teams: true,
    template_tasks: true,
    template_schedules: true,
    template_teams: true,
    templates: true,
    tasks: true,
    user: true,
    workflow_statuses: true,
    workflows: true,
  },
});
