/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgRouteRouteImport } from './routes/_org/route'
import { Route as OnboardingRouteRouteImport } from './routes/_onboarding/route'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as OrgSettingsRouteImport } from './routes/_org/settings'
import { Route as OrgOurWorkRouteImport } from './routes/_org/our-work'
import { Route as OrgMyWorkRouteImport } from './routes/_org/my-work'
import { Route as OnboardingOnboardingRouteImport } from './routes/_onboarding/onboarding'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as OrgTeamTeamIdRouteImport } from './routes/_org/team.$teamId'
import { Route as OrgSettingsTeamRouteImport } from './routes/_org/settings.team'
import { Route as OrgSettingsProfileRouteImport } from './routes/_org/settings.profile'
import { Route as OrgSettingsOrgRouteImport } from './routes/_org/settings.org'
import { Route as OrgSettingsTeamTeamTabRouteImport } from './routes/_org/settings.team.$teamTab'

const OrgRouteRoute = OrgRouteRouteImport.update({
  id: '/_org',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgOurWorkRoute = OrgOurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgMyWorkRoute = OrgMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OnboardingOnboardingRoute = OnboardingOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamTeamIdRoute = OrgTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgSettingsTeamRoute = OrgSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OrgSettingsRoute,
} as any)
const OrgSettingsProfileRoute = OrgSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OrgSettingsRoute,
} as any)
const OrgSettingsOrgRoute = OrgSettingsOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => OrgSettingsRoute,
} as any)
const OrgSettingsTeamTeamTabRoute = OrgSettingsTeamTeamTabRouteImport.update({
  id: '/$teamTab',
  path: '/$teamTab',
  getParentRoute: () => OrgSettingsTeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/my-work': typeof OrgMyWorkRoute
  '/our-work': typeof OrgOurWorkRoute
  '/settings': typeof OrgSettingsRouteWithChildren
  '/settings/org': typeof OrgSettingsOrgRoute
  '/settings/profile': typeof OrgSettingsProfileRoute
  '/settings/team': typeof OrgSettingsTeamRouteWithChildren
  '/team/$teamId': typeof OrgTeamTeamIdRoute
  '/settings/team/$teamTab': typeof OrgSettingsTeamTeamTabRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/my-work': typeof OrgMyWorkRoute
  '/our-work': typeof OrgOurWorkRoute
  '/settings': typeof OrgSettingsRouteWithChildren
  '/settings/org': typeof OrgSettingsOrgRoute
  '/settings/profile': typeof OrgSettingsProfileRoute
  '/settings/team': typeof OrgSettingsTeamRouteWithChildren
  '/team/$teamId': typeof OrgTeamTeamIdRoute
  '/settings/team/$teamTab': typeof OrgSettingsTeamTeamTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/_onboarding': typeof OnboardingRouteRouteWithChildren
  '/_org': typeof OrgRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/_org/my-work': typeof OrgMyWorkRoute
  '/_org/our-work': typeof OrgOurWorkRoute
  '/_org/settings': typeof OrgSettingsRouteWithChildren
  '/_marketing/': typeof MarketingIndexRoute
  '/_org/settings/org': typeof OrgSettingsOrgRoute
  '/_org/settings/profile': typeof OrgSettingsProfileRoute
  '/_org/settings/team': typeof OrgSettingsTeamRouteWithChildren
  '/_org/team/$teamId': typeof OrgTeamTeamIdRoute
  '/_org/settings/team/$teamTab': typeof OrgSettingsTeamTeamTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/onboarding'
    | '/my-work'
    | '/our-work'
    | '/settings'
    | '/settings/org'
    | '/settings/profile'
    | '/settings/team'
    | '/team/$teamId'
    | '/settings/team/$teamTab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/onboarding'
    | '/my-work'
    | '/our-work'
    | '/settings'
    | '/settings/org'
    | '/settings/profile'
    | '/settings/team'
    | '/team/$teamId'
    | '/settings/team/$teamTab'
  id:
    | '__root__'
    | '/_marketing'
    | '/_onboarding'
    | '/_org'
    | '/_auth/sign-in'
    | '/_onboarding/onboarding'
    | '/_org/my-work'
    | '/_org/our-work'
    | '/_org/settings'
    | '/_marketing/'
    | '/_org/settings/org'
    | '/_org/settings/profile'
    | '/_org/settings/team'
    | '/_org/team/$teamId'
    | '/_org/settings/team/$teamTab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  OrgRouteRoute: typeof OrgRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_org': {
      id: '/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrgRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_org/settings': {
      id: '/_org/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_org/our-work': {
      id: '/_org/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OrgOurWorkRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_org/my-work': {
      id: '/_org/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof OrgMyWorkRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_onboarding/onboarding': {
      id: '/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_org/team/$teamId': {
      id: '/_org/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof OrgTeamTeamIdRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_org/settings/team': {
      id: '/_org/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof OrgSettingsTeamRouteImport
      parentRoute: typeof OrgSettingsRoute
    }
    '/_org/settings/profile': {
      id: '/_org/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof OrgSettingsProfileRouteImport
      parentRoute: typeof OrgSettingsRoute
    }
    '/_org/settings/org': {
      id: '/_org/settings/org'
      path: '/org'
      fullPath: '/settings/org'
      preLoaderRoute: typeof OrgSettingsOrgRouteImport
      parentRoute: typeof OrgSettingsRoute
    }
    '/_org/settings/team/$teamTab': {
      id: '/_org/settings/team/$teamTab'
      path: '/$teamTab'
      fullPath: '/settings/team/$teamTab'
      preLoaderRoute: typeof OrgSettingsTeamTeamTabRouteImport
      parentRoute: typeof OrgSettingsTeamRoute
    }
  }
}

interface MarketingRouteRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingOnboardingRoute: typeof OnboardingOnboardingRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingOnboardingRoute: OnboardingOnboardingRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface OrgSettingsTeamRouteChildren {
  OrgSettingsTeamTeamTabRoute: typeof OrgSettingsTeamTeamTabRoute
}

const OrgSettingsTeamRouteChildren: OrgSettingsTeamRouteChildren = {
  OrgSettingsTeamTeamTabRoute: OrgSettingsTeamTeamTabRoute,
}

const OrgSettingsTeamRouteWithChildren = OrgSettingsTeamRoute._addFileChildren(
  OrgSettingsTeamRouteChildren,
)

interface OrgSettingsRouteChildren {
  OrgSettingsOrgRoute: typeof OrgSettingsOrgRoute
  OrgSettingsProfileRoute: typeof OrgSettingsProfileRoute
  OrgSettingsTeamRoute: typeof OrgSettingsTeamRouteWithChildren
}

const OrgSettingsRouteChildren: OrgSettingsRouteChildren = {
  OrgSettingsOrgRoute: OrgSettingsOrgRoute,
  OrgSettingsProfileRoute: OrgSettingsProfileRoute,
  OrgSettingsTeamRoute: OrgSettingsTeamRouteWithChildren,
}

const OrgSettingsRouteWithChildren = OrgSettingsRoute._addFileChildren(
  OrgSettingsRouteChildren,
)

interface OrgRouteRouteChildren {
  OrgMyWorkRoute: typeof OrgMyWorkRoute
  OrgOurWorkRoute: typeof OrgOurWorkRoute
  OrgSettingsRoute: typeof OrgSettingsRouteWithChildren
  OrgTeamTeamIdRoute: typeof OrgTeamTeamIdRoute
}

const OrgRouteRouteChildren: OrgRouteRouteChildren = {
  OrgMyWorkRoute: OrgMyWorkRoute,
  OrgOurWorkRoute: OrgOurWorkRoute,
  OrgSettingsRoute: OrgSettingsRouteWithChildren,
  OrgTeamTeamIdRoute: OrgTeamTeamIdRoute,
}

const OrgRouteRouteWithChildren = OrgRouteRoute._addFileChildren(
  OrgRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  OrgRouteRoute: OrgRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
