/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/_settings/route'
import { Route as OrgRouteRouteImport } from './routes/_org/route'
import { Route as OnboardingRouteRouteImport } from './routes/_onboarding/route'
import { Route as MarketingRouteRouteImport } from './routes/_marketing/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as SettingsSettingsRouteImport } from './routes/_settings/settings'
import { Route as OrgTemplatesRouteImport } from './routes/_org/templates'
import { Route as OrgOurWorkRouteImport } from './routes/_org/our-work'
import { Route as OrgMyWorkRouteImport } from './routes/_org/my-work'
import { Route as OrgAdminRouteImport } from './routes/_org/admin'
import { Route as OnboardingOnboardingRouteImport } from './routes/_onboarding/onboarding'
import { Route as MarketingLibraryRouteImport } from './routes/_marketing/library'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OrgTemplatesLibraryRouteImport } from './routes/_org/templates.library'
import { Route as OrgTemplatesKeyDatesRouteImport } from './routes/_org/templates.key-dates'
import { Route as OrgTemplatesTemplateIdRouteImport } from './routes/_org/templates.$templateId'
import { Route as OrgTeamTeamIdentifierRouteImport } from './routes/_org/team.$teamIdentifier'
import { Route as OrgDevSessionRouteImport } from './routes/_org/dev.session'
import { Route as OrgDevDataRouteImport } from './routes/_org/dev.data'
import { Route as OrgAdminUsersRouteImport } from './routes/_org/admin.users'
import { Route as OrgAdminOrgsRouteImport } from './routes/_org/admin.orgs'
import { Route as AuthAcceptInvitationIdRouteImport } from './routes/_auth/accept-invitation.$id'
import { Route as SettingsSettingsWorkspaceSchedulingRouteImport } from './routes/_settings/settings.workspace.scheduling'
import { Route as SettingsSettingsWorkspaceMembersRouteImport } from './routes/_settings/settings.workspace.members'
import { Route as SettingsSettingsWorkspaceLabelsRouteImport } from './routes/_settings/settings.workspace.labels'
import { Route as SettingsSettingsWorkspaceKeyDatesRouteImport } from './routes/_settings/settings.workspace.key-dates'
import { Route as SettingsSettingsWorkspaceGeneralRouteImport } from './routes/_settings/settings.workspace.general'
import { Route as SettingsSettingsTeamsTeamIdRouteImport } from './routes/_settings/settings.teams.$teamId'
import { Route as SettingsSettingsAccountProfileRouteImport } from './routes/_settings/settings.account.profile'
import { Route as OrgTeamTeamIdentifierWeeksRouteImport } from './routes/_org/team.$teamIdentifier_.weeks'
import { Route as SettingsSettingsTeamsTeamIdIndexRouteImport } from './routes/_settings/settings.teams.$teamId.index'
import { Route as SettingsSettingsTeamsTeamIdMembersRouteImport } from './routes/_settings/settings.teams.$teamId.members'
import { Route as SettingsSettingsTeamsTeamIdGeneralRouteImport } from './routes/_settings/settings.teams.$teamId.general'
import { Route as OrgTeamTeamIdentifierWeekWeekNumberRouteImport } from './routes/_org/team.$teamIdentifier_.week.$weekNumber'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/_settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRouteRoute = OrgRouteRouteImport.update({
  id: '/_org',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRouteRoute = MarketingRouteRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSettingsRoute = SettingsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const OrgTemplatesRoute = OrgTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgOurWorkRoute = OrgOurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgMyWorkRoute = OrgMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgAdminRoute = OrgAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OnboardingOnboardingRoute = OnboardingOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const MarketingLibraryRoute = MarketingLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => MarketingRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTemplatesLibraryRoute = OrgTemplatesLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => OrgTemplatesRoute,
} as any)
const OrgTemplatesKeyDatesRoute = OrgTemplatesKeyDatesRouteImport.update({
  id: '/key-dates',
  path: '/key-dates',
  getParentRoute: () => OrgTemplatesRoute,
} as any)
const OrgTemplatesTemplateIdRoute = OrgTemplatesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => OrgTemplatesRoute,
} as any)
const OrgTeamTeamIdentifierRoute = OrgTeamTeamIdentifierRouteImport.update({
  id: '/team/$teamIdentifier',
  path: '/team/$teamIdentifier',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgDevSessionRoute = OrgDevSessionRouteImport.update({
  id: '/dev/session',
  path: '/dev/session',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgDevDataRoute = OrgDevDataRouteImport.update({
  id: '/dev/data',
  path: '/dev/data',
  getParentRoute: () => OrgRouteRoute,
} as any)
const OrgAdminUsersRoute = OrgAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OrgAdminRoute,
} as any)
const OrgAdminOrgsRoute = OrgAdminOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => OrgAdminRoute,
} as any)
const AuthAcceptInvitationIdRoute = AuthAcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SettingsSettingsWorkspaceSchedulingRoute =
  SettingsSettingsWorkspaceSchedulingRouteImport.update({
    id: '/workspace/scheduling',
    path: '/workspace/scheduling',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsWorkspaceMembersRoute =
  SettingsSettingsWorkspaceMembersRouteImport.update({
    id: '/workspace/members',
    path: '/workspace/members',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsWorkspaceLabelsRoute =
  SettingsSettingsWorkspaceLabelsRouteImport.update({
    id: '/workspace/labels',
    path: '/workspace/labels',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsWorkspaceKeyDatesRoute =
  SettingsSettingsWorkspaceKeyDatesRouteImport.update({
    id: '/workspace/key-dates',
    path: '/workspace/key-dates',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsWorkspaceGeneralRoute =
  SettingsSettingsWorkspaceGeneralRouteImport.update({
    id: '/workspace/general',
    path: '/workspace/general',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsTeamsTeamIdRoute =
  SettingsSettingsTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsAccountProfileRoute =
  SettingsSettingsAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const OrgTeamTeamIdentifierWeeksRoute =
  OrgTeamTeamIdentifierWeeksRouteImport.update({
    id: '/team/$teamIdentifier_/weeks',
    path: '/team/$teamIdentifier/weeks',
    getParentRoute: () => OrgRouteRoute,
  } as any)
const SettingsSettingsTeamsTeamIdIndexRoute =
  SettingsSettingsTeamsTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsSettingsTeamsTeamIdRoute,
  } as any)
const SettingsSettingsTeamsTeamIdMembersRoute =
  SettingsSettingsTeamsTeamIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => SettingsSettingsTeamsTeamIdRoute,
  } as any)
const SettingsSettingsTeamsTeamIdGeneralRoute =
  SettingsSettingsTeamsTeamIdGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => SettingsSettingsTeamsTeamIdRoute,
  } as any)
const OrgTeamTeamIdentifierWeekWeekNumberRoute =
  OrgTeamTeamIdentifierWeekWeekNumberRouteImport.update({
    id: '/team/$teamIdentifier_/week/$weekNumber',
    path: '/team/$teamIdentifier/week/$weekNumber',
    getParentRoute: () => OrgRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/library': typeof MarketingLibraryRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/admin': typeof OrgAdminRouteWithChildren
  '/my-work': typeof OrgMyWorkRoute
  '/our-work': typeof OrgOurWorkRoute
  '/templates': typeof OrgTemplatesRouteWithChildren
  '/settings': typeof SettingsSettingsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/accept-invitation/$id': typeof AuthAcceptInvitationIdRoute
  '/admin/orgs': typeof OrgAdminOrgsRoute
  '/admin/users': typeof OrgAdminUsersRoute
  '/dev/data': typeof OrgDevDataRoute
  '/dev/session': typeof OrgDevSessionRoute
  '/team/$teamIdentifier': typeof OrgTeamTeamIdentifierRoute
  '/templates/$templateId': typeof OrgTemplatesTemplateIdRoute
  '/templates/key-dates': typeof OrgTemplatesKeyDatesRoute
  '/templates/library': typeof OrgTemplatesLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/team/$teamIdentifier/weeks': typeof OrgTeamTeamIdentifierWeeksRoute
  '/settings/account/profile': typeof SettingsSettingsAccountProfileRoute
  '/settings/teams/$teamId': typeof SettingsSettingsTeamsTeamIdRouteWithChildren
  '/settings/workspace/general': typeof SettingsSettingsWorkspaceGeneralRoute
  '/settings/workspace/key-dates': typeof SettingsSettingsWorkspaceKeyDatesRoute
  '/settings/workspace/labels': typeof SettingsSettingsWorkspaceLabelsRoute
  '/settings/workspace/members': typeof SettingsSettingsWorkspaceMembersRoute
  '/settings/workspace/scheduling': typeof SettingsSettingsWorkspaceSchedulingRoute
  '/team/$teamIdentifier/week/$weekNumber': typeof OrgTeamTeamIdentifierWeekWeekNumberRoute
  '/settings/teams/$teamId/general': typeof SettingsSettingsTeamsTeamIdGeneralRoute
  '/settings/teams/$teamId/members': typeof SettingsSettingsTeamsTeamIdMembersRoute
  '/settings/teams/$teamId/': typeof SettingsSettingsTeamsTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/library': typeof MarketingLibraryRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/admin': typeof OrgAdminRouteWithChildren
  '/my-work': typeof OrgMyWorkRoute
  '/our-work': typeof OrgOurWorkRoute
  '/templates': typeof OrgTemplatesRouteWithChildren
  '/settings': typeof SettingsSettingsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/accept-invitation/$id': typeof AuthAcceptInvitationIdRoute
  '/admin/orgs': typeof OrgAdminOrgsRoute
  '/admin/users': typeof OrgAdminUsersRoute
  '/dev/data': typeof OrgDevDataRoute
  '/dev/session': typeof OrgDevSessionRoute
  '/team/$teamIdentifier': typeof OrgTeamTeamIdentifierRoute
  '/templates/$templateId': typeof OrgTemplatesTemplateIdRoute
  '/templates/key-dates': typeof OrgTemplatesKeyDatesRoute
  '/templates/library': typeof OrgTemplatesLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/team/$teamIdentifier/weeks': typeof OrgTeamTeamIdentifierWeeksRoute
  '/settings/account/profile': typeof SettingsSettingsAccountProfileRoute
  '/settings/workspace/general': typeof SettingsSettingsWorkspaceGeneralRoute
  '/settings/workspace/key-dates': typeof SettingsSettingsWorkspaceKeyDatesRoute
  '/settings/workspace/labels': typeof SettingsSettingsWorkspaceLabelsRoute
  '/settings/workspace/members': typeof SettingsSettingsWorkspaceMembersRoute
  '/settings/workspace/scheduling': typeof SettingsSettingsWorkspaceSchedulingRoute
  '/team/$teamIdentifier/week/$weekNumber': typeof OrgTeamTeamIdentifierWeekWeekNumberRoute
  '/settings/teams/$teamId/general': typeof SettingsSettingsTeamsTeamIdGeneralRoute
  '/settings/teams/$teamId/members': typeof SettingsSettingsTeamsTeamIdMembersRoute
  '/settings/teams/$teamId': typeof SettingsSettingsTeamsTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteRouteWithChildren
  '/_onboarding': typeof OnboardingRouteRouteWithChildren
  '/_org': typeof OrgRouteRouteWithChildren
  '/_settings': typeof SettingsRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_marketing/library': typeof MarketingLibraryRoute
  '/_onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/_org/admin': typeof OrgAdminRouteWithChildren
  '/_org/my-work': typeof OrgMyWorkRoute
  '/_org/our-work': typeof OrgOurWorkRoute
  '/_org/templates': typeof OrgTemplatesRouteWithChildren
  '/_settings/settings': typeof SettingsSettingsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_auth/accept-invitation/$id': typeof AuthAcceptInvitationIdRoute
  '/_org/admin/orgs': typeof OrgAdminOrgsRoute
  '/_org/admin/users': typeof OrgAdminUsersRoute
  '/_org/dev/data': typeof OrgDevDataRoute
  '/_org/dev/session': typeof OrgDevSessionRoute
  '/_org/team/$teamIdentifier': typeof OrgTeamTeamIdentifierRoute
  '/_org/templates/$templateId': typeof OrgTemplatesTemplateIdRoute
  '/_org/templates/key-dates': typeof OrgTemplatesKeyDatesRoute
  '/_org/templates/library': typeof OrgTemplatesLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_org/team/$teamIdentifier_/weeks': typeof OrgTeamTeamIdentifierWeeksRoute
  '/_settings/settings/account/profile': typeof SettingsSettingsAccountProfileRoute
  '/_settings/settings/teams/$teamId': typeof SettingsSettingsTeamsTeamIdRouteWithChildren
  '/_settings/settings/workspace/general': typeof SettingsSettingsWorkspaceGeneralRoute
  '/_settings/settings/workspace/key-dates': typeof SettingsSettingsWorkspaceKeyDatesRoute
  '/_settings/settings/workspace/labels': typeof SettingsSettingsWorkspaceLabelsRoute
  '/_settings/settings/workspace/members': typeof SettingsSettingsWorkspaceMembersRoute
  '/_settings/settings/workspace/scheduling': typeof SettingsSettingsWorkspaceSchedulingRoute
  '/_org/team/$teamIdentifier_/week/$weekNumber': typeof OrgTeamTeamIdentifierWeekWeekNumberRoute
  '/_settings/settings/teams/$teamId/general': typeof SettingsSettingsTeamsTeamIdGeneralRoute
  '/_settings/settings/teams/$teamId/members': typeof SettingsSettingsTeamsTeamIdMembersRoute
  '/_settings/settings/teams/$teamId/': typeof SettingsSettingsTeamsTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/library'
    | '/onboarding'
    | '/admin'
    | '/my-work'
    | '/our-work'
    | '/templates'
    | '/settings'
    | '/api/$'
    | '/accept-invitation/$id'
    | '/admin/orgs'
    | '/admin/users'
    | '/dev/data'
    | '/dev/session'
    | '/team/$teamIdentifier'
    | '/templates/$templateId'
    | '/templates/key-dates'
    | '/templates/library'
    | '/api/auth/$'
    | '/team/$teamIdentifier/weeks'
    | '/settings/account/profile'
    | '/settings/teams/$teamId'
    | '/settings/workspace/general'
    | '/settings/workspace/key-dates'
    | '/settings/workspace/labels'
    | '/settings/workspace/members'
    | '/settings/workspace/scheduling'
    | '/team/$teamIdentifier/week/$weekNumber'
    | '/settings/teams/$teamId/general'
    | '/settings/teams/$teamId/members'
    | '/settings/teams/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/library'
    | '/onboarding'
    | '/admin'
    | '/my-work'
    | '/our-work'
    | '/templates'
    | '/settings'
    | '/api/$'
    | '/accept-invitation/$id'
    | '/admin/orgs'
    | '/admin/users'
    | '/dev/data'
    | '/dev/session'
    | '/team/$teamIdentifier'
    | '/templates/$templateId'
    | '/templates/key-dates'
    | '/templates/library'
    | '/api/auth/$'
    | '/team/$teamIdentifier/weeks'
    | '/settings/account/profile'
    | '/settings/workspace/general'
    | '/settings/workspace/key-dates'
    | '/settings/workspace/labels'
    | '/settings/workspace/members'
    | '/settings/workspace/scheduling'
    | '/team/$teamIdentifier/week/$weekNumber'
    | '/settings/teams/$teamId/general'
    | '/settings/teams/$teamId/members'
    | '/settings/teams/$teamId'
  id:
    | '__root__'
    | '/_auth'
    | '/_marketing'
    | '/_onboarding'
    | '/_org'
    | '/_settings'
    | '/_auth/sign-in'
    | '/_marketing/library'
    | '/_onboarding/onboarding'
    | '/_org/admin'
    | '/_org/my-work'
    | '/_org/our-work'
    | '/_org/templates'
    | '/_settings/settings'
    | '/api/$'
    | '/_marketing/'
    | '/_auth/accept-invitation/$id'
    | '/_org/admin/orgs'
    | '/_org/admin/users'
    | '/_org/dev/data'
    | '/_org/dev/session'
    | '/_org/team/$teamIdentifier'
    | '/_org/templates/$templateId'
    | '/_org/templates/key-dates'
    | '/_org/templates/library'
    | '/api/auth/$'
    | '/_org/team/$teamIdentifier_/weeks'
    | '/_settings/settings/account/profile'
    | '/_settings/settings/teams/$teamId'
    | '/_settings/settings/workspace/general'
    | '/_settings/settings/workspace/key-dates'
    | '/_settings/settings/workspace/labels'
    | '/_settings/settings/workspace/members'
    | '/_settings/settings/workspace/scheduling'
    | '/_org/team/$teamIdentifier_/week/$weekNumber'
    | '/_settings/settings/teams/$teamId/general'
    | '/_settings/settings/teams/$teamId/members'
    | '/_settings/settings/teams/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MarketingRouteRoute: typeof MarketingRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  OrgRouteRoute: typeof OrgRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_settings': {
      id: '/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_org': {
      id: '/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrgRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settings/settings': {
      id: '/_settings/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsSettingsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_org/templates': {
      id: '/_org/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof OrgTemplatesRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_org/our-work': {
      id: '/_org/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OrgOurWorkRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_org/my-work': {
      id: '/_org/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof OrgMyWorkRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_org/admin': {
      id: '/_org/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof OrgAdminRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_onboarding/onboarding': {
      id: '/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_marketing/library': {
      id: '/_marketing/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof MarketingLibraryRouteImport
      parentRoute: typeof MarketingRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_org/templates/library': {
      id: '/_org/templates/library'
      path: '/library'
      fullPath: '/templates/library'
      preLoaderRoute: typeof OrgTemplatesLibraryRouteImport
      parentRoute: typeof OrgTemplatesRoute
    }
    '/_org/templates/key-dates': {
      id: '/_org/templates/key-dates'
      path: '/key-dates'
      fullPath: '/templates/key-dates'
      preLoaderRoute: typeof OrgTemplatesKeyDatesRouteImport
      parentRoute: typeof OrgTemplatesRoute
    }
    '/_org/templates/$templateId': {
      id: '/_org/templates/$templateId'
      path: '/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof OrgTemplatesTemplateIdRouteImport
      parentRoute: typeof OrgTemplatesRoute
    }
    '/_org/team/$teamIdentifier': {
      id: '/_org/team/$teamIdentifier'
      path: '/team/$teamIdentifier'
      fullPath: '/team/$teamIdentifier'
      preLoaderRoute: typeof OrgTeamTeamIdentifierRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_org/dev/session': {
      id: '/_org/dev/session'
      path: '/dev/session'
      fullPath: '/dev/session'
      preLoaderRoute: typeof OrgDevSessionRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_org/dev/data': {
      id: '/_org/dev/data'
      path: '/dev/data'
      fullPath: '/dev/data'
      preLoaderRoute: typeof OrgDevDataRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_org/admin/users': {
      id: '/_org/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof OrgAdminUsersRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/_org/admin/orgs': {
      id: '/_org/admin/orgs'
      path: '/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof OrgAdminOrgsRouteImport
      parentRoute: typeof OrgAdminRoute
    }
    '/_auth/accept-invitation/$id': {
      id: '/_auth/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AuthAcceptInvitationIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_settings/settings/workspace/scheduling': {
      id: '/_settings/settings/workspace/scheduling'
      path: '/workspace/scheduling'
      fullPath: '/settings/workspace/scheduling'
      preLoaderRoute: typeof SettingsSettingsWorkspaceSchedulingRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/workspace/members': {
      id: '/_settings/settings/workspace/members'
      path: '/workspace/members'
      fullPath: '/settings/workspace/members'
      preLoaderRoute: typeof SettingsSettingsWorkspaceMembersRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/workspace/labels': {
      id: '/_settings/settings/workspace/labels'
      path: '/workspace/labels'
      fullPath: '/settings/workspace/labels'
      preLoaderRoute: typeof SettingsSettingsWorkspaceLabelsRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/workspace/key-dates': {
      id: '/_settings/settings/workspace/key-dates'
      path: '/workspace/key-dates'
      fullPath: '/settings/workspace/key-dates'
      preLoaderRoute: typeof SettingsSettingsWorkspaceKeyDatesRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/workspace/general': {
      id: '/_settings/settings/workspace/general'
      path: '/workspace/general'
      fullPath: '/settings/workspace/general'
      preLoaderRoute: typeof SettingsSettingsWorkspaceGeneralRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/teams/$teamId': {
      id: '/_settings/settings/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/settings/teams/$teamId'
      preLoaderRoute: typeof SettingsSettingsTeamsTeamIdRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/account/profile': {
      id: '/_settings/settings/account/profile'
      path: '/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof SettingsSettingsAccountProfileRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_org/team/$teamIdentifier_/weeks': {
      id: '/_org/team/$teamIdentifier_/weeks'
      path: '/team/$teamIdentifier/weeks'
      fullPath: '/team/$teamIdentifier/weeks'
      preLoaderRoute: typeof OrgTeamTeamIdentifierWeeksRouteImport
      parentRoute: typeof OrgRouteRoute
    }
    '/_settings/settings/teams/$teamId/': {
      id: '/_settings/settings/teams/$teamId/'
      path: '/'
      fullPath: '/settings/teams/$teamId/'
      preLoaderRoute: typeof SettingsSettingsTeamsTeamIdIndexRouteImport
      parentRoute: typeof SettingsSettingsTeamsTeamIdRoute
    }
    '/_settings/settings/teams/$teamId/members': {
      id: '/_settings/settings/teams/$teamId/members'
      path: '/members'
      fullPath: '/settings/teams/$teamId/members'
      preLoaderRoute: typeof SettingsSettingsTeamsTeamIdMembersRouteImport
      parentRoute: typeof SettingsSettingsTeamsTeamIdRoute
    }
    '/_settings/settings/teams/$teamId/general': {
      id: '/_settings/settings/teams/$teamId/general'
      path: '/general'
      fullPath: '/settings/teams/$teamId/general'
      preLoaderRoute: typeof SettingsSettingsTeamsTeamIdGeneralRouteImport
      parentRoute: typeof SettingsSettingsTeamsTeamIdRoute
    }
    '/_org/team/$teamIdentifier_/week/$weekNumber': {
      id: '/_org/team/$teamIdentifier_/week/$weekNumber'
      path: '/team/$teamIdentifier/week/$weekNumber'
      fullPath: '/team/$teamIdentifier/week/$weekNumber'
      preLoaderRoute: typeof OrgTeamTeamIdentifierWeekWeekNumberRouteImport
      parentRoute: typeof OrgRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthAcceptInvitationIdRoute: typeof AuthAcceptInvitationIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthAcceptInvitationIdRoute: AuthAcceptInvitationIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MarketingRouteRouteChildren {
  MarketingLibraryRoute: typeof MarketingLibraryRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteRouteChildren: MarketingRouteRouteChildren = {
  MarketingLibraryRoute: MarketingLibraryRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteRouteWithChildren = MarketingRouteRoute._addFileChildren(
  MarketingRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingOnboardingRoute: typeof OnboardingOnboardingRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingOnboardingRoute: OnboardingOnboardingRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface OrgAdminRouteChildren {
  OrgAdminOrgsRoute: typeof OrgAdminOrgsRoute
  OrgAdminUsersRoute: typeof OrgAdminUsersRoute
}

const OrgAdminRouteChildren: OrgAdminRouteChildren = {
  OrgAdminOrgsRoute: OrgAdminOrgsRoute,
  OrgAdminUsersRoute: OrgAdminUsersRoute,
}

const OrgAdminRouteWithChildren = OrgAdminRoute._addFileChildren(
  OrgAdminRouteChildren,
)

interface OrgTemplatesRouteChildren {
  OrgTemplatesTemplateIdRoute: typeof OrgTemplatesTemplateIdRoute
  OrgTemplatesKeyDatesRoute: typeof OrgTemplatesKeyDatesRoute
  OrgTemplatesLibraryRoute: typeof OrgTemplatesLibraryRoute
}

const OrgTemplatesRouteChildren: OrgTemplatesRouteChildren = {
  OrgTemplatesTemplateIdRoute: OrgTemplatesTemplateIdRoute,
  OrgTemplatesKeyDatesRoute: OrgTemplatesKeyDatesRoute,
  OrgTemplatesLibraryRoute: OrgTemplatesLibraryRoute,
}

const OrgTemplatesRouteWithChildren = OrgTemplatesRoute._addFileChildren(
  OrgTemplatesRouteChildren,
)

interface OrgRouteRouteChildren {
  OrgAdminRoute: typeof OrgAdminRouteWithChildren
  OrgMyWorkRoute: typeof OrgMyWorkRoute
  OrgOurWorkRoute: typeof OrgOurWorkRoute
  OrgTemplatesRoute: typeof OrgTemplatesRouteWithChildren
  OrgDevDataRoute: typeof OrgDevDataRoute
  OrgDevSessionRoute: typeof OrgDevSessionRoute
  OrgTeamTeamIdentifierRoute: typeof OrgTeamTeamIdentifierRoute
  OrgTeamTeamIdentifierWeeksRoute: typeof OrgTeamTeamIdentifierWeeksRoute
  OrgTeamTeamIdentifierWeekWeekNumberRoute: typeof OrgTeamTeamIdentifierWeekWeekNumberRoute
}

const OrgRouteRouteChildren: OrgRouteRouteChildren = {
  OrgAdminRoute: OrgAdminRouteWithChildren,
  OrgMyWorkRoute: OrgMyWorkRoute,
  OrgOurWorkRoute: OrgOurWorkRoute,
  OrgTemplatesRoute: OrgTemplatesRouteWithChildren,
  OrgDevDataRoute: OrgDevDataRoute,
  OrgDevSessionRoute: OrgDevSessionRoute,
  OrgTeamTeamIdentifierRoute: OrgTeamTeamIdentifierRoute,
  OrgTeamTeamIdentifierWeeksRoute: OrgTeamTeamIdentifierWeeksRoute,
  OrgTeamTeamIdentifierWeekWeekNumberRoute:
    OrgTeamTeamIdentifierWeekWeekNumberRoute,
}

const OrgRouteRouteWithChildren = OrgRouteRoute._addFileChildren(
  OrgRouteRouteChildren,
)

interface SettingsSettingsTeamsTeamIdRouteChildren {
  SettingsSettingsTeamsTeamIdGeneralRoute: typeof SettingsSettingsTeamsTeamIdGeneralRoute
  SettingsSettingsTeamsTeamIdMembersRoute: typeof SettingsSettingsTeamsTeamIdMembersRoute
  SettingsSettingsTeamsTeamIdIndexRoute: typeof SettingsSettingsTeamsTeamIdIndexRoute
}

const SettingsSettingsTeamsTeamIdRouteChildren: SettingsSettingsTeamsTeamIdRouteChildren =
  {
    SettingsSettingsTeamsTeamIdGeneralRoute:
      SettingsSettingsTeamsTeamIdGeneralRoute,
    SettingsSettingsTeamsTeamIdMembersRoute:
      SettingsSettingsTeamsTeamIdMembersRoute,
    SettingsSettingsTeamsTeamIdIndexRoute:
      SettingsSettingsTeamsTeamIdIndexRoute,
  }

const SettingsSettingsTeamsTeamIdRouteWithChildren =
  SettingsSettingsTeamsTeamIdRoute._addFileChildren(
    SettingsSettingsTeamsTeamIdRouteChildren,
  )

interface SettingsSettingsRouteChildren {
  SettingsSettingsAccountProfileRoute: typeof SettingsSettingsAccountProfileRoute
  SettingsSettingsTeamsTeamIdRoute: typeof SettingsSettingsTeamsTeamIdRouteWithChildren
  SettingsSettingsWorkspaceGeneralRoute: typeof SettingsSettingsWorkspaceGeneralRoute
  SettingsSettingsWorkspaceKeyDatesRoute: typeof SettingsSettingsWorkspaceKeyDatesRoute
  SettingsSettingsWorkspaceLabelsRoute: typeof SettingsSettingsWorkspaceLabelsRoute
  SettingsSettingsWorkspaceMembersRoute: typeof SettingsSettingsWorkspaceMembersRoute
  SettingsSettingsWorkspaceSchedulingRoute: typeof SettingsSettingsWorkspaceSchedulingRoute
}

const SettingsSettingsRouteChildren: SettingsSettingsRouteChildren = {
  SettingsSettingsAccountProfileRoute: SettingsSettingsAccountProfileRoute,
  SettingsSettingsTeamsTeamIdRoute:
    SettingsSettingsTeamsTeamIdRouteWithChildren,
  SettingsSettingsWorkspaceGeneralRoute: SettingsSettingsWorkspaceGeneralRoute,
  SettingsSettingsWorkspaceKeyDatesRoute:
    SettingsSettingsWorkspaceKeyDatesRoute,
  SettingsSettingsWorkspaceLabelsRoute: SettingsSettingsWorkspaceLabelsRoute,
  SettingsSettingsWorkspaceMembersRoute: SettingsSettingsWorkspaceMembersRoute,
  SettingsSettingsWorkspaceSchedulingRoute:
    SettingsSettingsWorkspaceSchedulingRoute,
}

const SettingsSettingsRouteWithChildren =
  SettingsSettingsRoute._addFileChildren(SettingsSettingsRouteChildren)

interface SettingsRouteRouteChildren {
  SettingsSettingsRoute: typeof SettingsSettingsRouteWithChildren
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsSettingsRoute: SettingsSettingsRouteWithChildren,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MarketingRouteRoute: MarketingRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  OrgRouteRoute: OrgRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
